### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by jpoa** [trinhanhngoc/odoo-stubs#1]
Greetings,

Maybe I am missing something here, could you please let me know how I can test if it is installed ok?

Best regards

**Comment by trinhanhngoc** [comment]
If you are using PyCharm, you should add this stubs (select the branch that corresponds to the odoo version) as a content root of the odoo source code in your project.

![Screenshot from 2020-05-21 20-47-29](https://user-images.githubusercontent.com/11208291/82565402-91b93f80-9ba4-11ea-801a-61a15a152666.png)
