### ISSUE TITLE
v12.0 vs v13.0

### ISSUE THREAD

**Issue by izotecarlitos** [trinhanhngoc/odoo-stubs#2]
Hi, 
I am wondering if v12.0 works with all versions of Odoo? Or odoo-stubs v12 should be used only with v12 of odoo? and odoo-stubs v13 should only be used with v13 of odoo?

Thanks, 

Carlos

**Comment by ngoctrinh-viindoo** [comment]
Yes. You should use the branch corresponding to the odoo version:

- odoo-stubs v12 is for Odoo 12
- odoo-stubs v13 is for Odoo 13
...
