### ISSUE TITLE
Pycharm gives warning when using models.ValidationError

### ISSUE THREAD

**Issue by jcBalmes92** [trinhanhngoc/odoo-stubs#5]
Pycharm gives warning when using models.ValidationError
![image](https://user-images.githubusercontent.com/75234645/122851729-79eb4800-d2dd-11eb-98ab-2a5bf70a5630.png)

**Comment by trinhanhngoc** [comment]
> Pycharm gives warning when using models.ValidationError
> ![image](https://user-images.githubusercontent.com/75234645/122851729-79eb4800-d2dd-11eb-98ab-2a5bf70a5630.png)

You are referencing `ValidationError` from wrong module. To use `ValidationError`, the correct import is:

```python
from odoo.exceptions import ValidationError
```

**Comment by jcBalmes92** [comment]
On models there's also this import
`from .exceptions import AccessError, MissingError, ValidationError, UserError`

But I guess that's also another way. Thanks.
